/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\right-mirror.glb --transform
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { MathUtils } from 'three'
import { useFrame } from '@react-three/fiber'

export function RightMirror(props) {
  const { nodes, materials } = useGLTF('/right-mirror-transformed.glb')
  const [hovered, setHovered] = useState(false)
  const ref = useRef()

  useFrame(() => {
    ref.current.children[0].material.transparent = true
    ref.current.children[1].material.transparent = true
    ref.current.children[0].material.opacity = MathUtils.lerp(ref.current.children[0].material.opacity, hovered ? 1 : 0.2, 0.025)
    ref.current.children[1].material.opacity = MathUtils.lerp(ref.current.children[1].material.opacity, hovered ? 1 : 0.2, 0.025)
  })

  return (
    <group 
      {...props} 
      dispose={null}
      onPointerOver={() => setHovered(true)}
      onPointerOut={() => setHovered(false)}
    >
      <group ref={ref} position={[-8.006, 2.223, 8.464]} rotation={[Math.PI / 2, 0, 0.843]} scale={[3.012, 0.112, 2.856]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials['Glass.003']} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['Material.008']} />
      </group>
    </group>
  )
}

useGLTF.preload('/right-mirror-transformed.glb')
