/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 .\public\right-door.glb --transform scale [0.25, 0.25, 0.25]
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { Color, MathUtils, Vector3 } from 'three'
import { useFrame, useThree } from '@react-three/fiber'
import { selectSceneHistory, setCurrentScene, setSceneHistory } from '../../../slices/scene'
import { useDispatch, useSelector } from 'react-redux'

const vec = new Vector3()
const black = new Color('black')
const white = new Color('white')

export function RightDoor(props) {
  const { nodes, materials } = useGLTF('/right-door-transformed.glb')
  const mirrorRef = useRef()

  const [hovered, setHovered] = useState(false)
  const [selected, setSelected] = useState(false)
  const dispatch = useDispatch() 
  const history = useSelector(selectSceneHistory)

  useFrame(({ camera }) => {
    mirrorRef.current.children[0].material.color.lerp(hovered ? black : white, 0.025)

    if (selected) {
      vec.set(4.918, 0, -7.44)
      camera.position.lerp(vec, 0.015)
    }
  })

  const handleClick = () => {
    setTimeout(() => {
      dispatch(setCurrentScene(2))
      if (!history.some(scene => scene.sceneNumber === 2))
        dispatch(setSceneHistory([...history, { name: 'The Auracle', sceneNumber: 2 }]))
    }, 1500)
  }

  return (
    <group
      onClick={() => { setSelected(true) ; handleClick()}}
      onPointerOver={() => setHovered(true)}
      onPointerOut={() => setHovered(false)} 
     {...props} dispose={null}>
      <mesh geometry={nodes.StoneGateway001.geometry} material={materials['monastery_stone_floor.001']} position={[4.918, 2.529, -7.44]} rotation={[-Math.PI / 2, 0, -0.741]} scale={-1} />
      <group ref={mirrorRef} position={[4.858, -0.448, -7.382]} rotation={[-0.003, -0.692, -0.029]} scale={6.655}>
        <mesh geometry={nodes.mesh004.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.mesh004_1.geometry} material={materials.PaletteMaterial002} />
      </group>
    </group>
  )
}

useGLTF.preload('/right-door-transformed.glb')