/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\asteroid-body-draco.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/asteroid-body-draco-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Asterioid_Body.geometry} material={materials['Asteroid Rock.002']} position={[0, -8.153, 0.097]} scale={8} />
    </group>
  )
}

useGLTF.preload('/asteroid-body-draco-transformed.glb')
