/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\dome-draco.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/dome-draco-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Black and gold marble']} position={[0, -0.122, 0]} scale={[9.939, 0.099, 9.939]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Green marble']} position={[0.002, 6.12, 5.487]} scale={[6, 1.2, 6]} />
      <mesh geometry={nodes.Floor.geometry} material={materials['Artificial Marble 1']} position={[0, -0.522, 5.444]} scale={[7.121, 0.408, 7.121]} />
      <mesh geometry={nodes.Roof.geometry} material={materials['Black and gold marble']} position={[0.088, 6.564, 5.32]} scale={5} />
    </group>
  )
}

useGLTF.preload('/dome-draco-transformed.glb')
