/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\themis-shrine-draco.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/themis-shrine-draco-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.011, -1.014, 0.141]} scale={2}>
        <mesh geometry={nodes.Cylinder.geometry} material={materials['Cracked glass']} />
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Artificial Marble 8']} />
      </group>
      <group position={[0.011, 3.038, 0.141]} scale={[1.627, 2, 1.627]}>
        <mesh geometry={nodes.Cylinder005.geometry} material={materials['Stone Tiles']} />
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials.Stone} />
      </group>
      <mesh geometry={nodes.Chains001.geometry} material={materials['Material.004']} position={[0.038, 7.049, 0.178]} rotation={[-0.391, 0.053, 0.008]} scale={0.034} />
      <mesh geometry={nodes.Themis_Sculpture.geometry} material={materials['Material.003']} position={[0.011, 2.128, 0.07]} scale={2} />
    </group>
  )
}

useGLTF.preload('/themis-shrine-draco-transformed.glb')
