/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 .\public\background-draco.glb --transform scale [0.25, 0.25, 0.25]
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Background(props) {
  const { nodes, materials } = useGLTF('/background-draco-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.EXPORT_GOOGLE_SAT_WM.geometry} material={materials.coast_sand_rocks_02} position={[1.507, -19.403, -24.072]} rotation={[0.572, 0.017, 3.126]} scale={-0.019} />
      <mesh geometry={nodes.dome.geometry} material={materials['Material.001']} position={[-0.128, 3.839, 2.079]} rotation={[-Math.PI / 2, 0, 1.571]} scale={-0.083} />
    </group>
  )
}

useGLTF.preload('/background-draco-transformed.glb')
