/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 .\public\dome-draco.glb --transform scale: [0.25, 0.25, 0.25]
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Dome(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/dome-draco-transformed.glb')

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="dome" geometry={nodes.dome.geometry} material={materials['Material.001']} position={[0.555, 5.199, 0.08]} rotation={[Math.PI / 2, 0, -2.979]} scale={0.083} />
      </group>
    </group>
  )
}

useGLTF.preload('/dome-draco-transformed.glb')
