/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 .\public\floor-draco.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Floor(props) {
  const { nodes, materials } = useGLTF('/floor-draco-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={materials.coast_sand_rocks_02} />
    </group>
  )
}

useGLTF.preload('/floor-draco-transformed.glb')