/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 .\public\wednesday-draco.glb --transform scale: [0.05, 0.05, 0.05]
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Wednesday(props) {
  const { nodes, materials } = useGLTF('/wednesday-draco-transformed.glb')

  return (
    <group {...props} dispose={null}>
      <group position={[0, 2.318, -0.011]} rotation={[-Math.PI, -1.507, -Math.PI]} scale={0.163}>
        <mesh geometry={nodes.Plane007.geometry} material={materials['mesh.002']} />
        <mesh geometry={nodes.Plane007_1.geometry} material={materials['cloth.mesh']} />
        <mesh geometry={nodes.Plane007_2.geometry} material={materials['Cloth.Dark.Stripes']} />
        <mesh geometry={nodes.Plane007_3.geometry} material={materials['Cloth.Black.Leather']} />
        <mesh geometry={nodes.Plane007_4.geometry} material={materials.Leather} />
        <mesh geometry={nodes.Plane007_5.geometry} material={materials.PaletteMaterial001} />
      </group>
      <mesh geometry={nodes.ClothShoes.geometry} material={materials['Cloth.white']} position={[0, 2.318, -0.011]} rotation={[-Math.PI, -1.507, -Math.PI]} scale={0.163} />
      <group position={[-0.131, 2.37, 0.021]} rotation={[-1.574, 0.071, -1.53]} scale={0.024}>
        <mesh geometry={nodes.Eye001.geometry} material={materials['Eye.001']} />
        <mesh geometry={nodes.Eye001_1.geometry} material={materials.PaletteMaterial002} />
      </group>
      <mesh geometry={nodes.EyeBrow.geometry} material={materials['Eyebrows.001']} position={[0, 2.318, -0.011]} rotation={[-Math.PI, -1.507, -Math.PI]} scale={0.163} />
      <mesh geometry={nodes.Eyelashes.geometry} material={materials['EyeLashes.001']} position={[0, 2.318, -0.011]} rotation={[-Math.PI, -1.507, -Math.PI]} scale={0.163} />
      <group position={[0, 2.318, -0.011]} rotation={[-Math.PI, -1.507, -Math.PI]} scale={0.163}>
        <mesh geometry={nodes.GIrlBasemesh005.geometry} material={materials['Face.001']} />
        <mesh geometry={nodes.GIrlBasemesh005_1.geometry} material={materials['Skin.001']} />
      </group>
      <mesh geometry={nodes.HairBraid.geometry} material={materials['Hair.001']} position={[0, 2.318, -0.011]} rotation={[-Math.PI, -1.507, -Math.PI]} scale={0.163} />
      <mesh geometry={nodes.Hairfront.geometry} material={materials['Hair.001']} position={[-0.096, 2.483, -0.071]} rotation={[2.981, -0.707, -3.009]} scale={[-0.075, 0.24, 0.24]} />
      <mesh geometry={nodes.HairCap.geometry} material={materials['Hair.002']} position={[-0.025, 2.425, -0.013]} rotation={[-Math.PI, -1.507, -Math.PI]} scale={0.167} />
      <group position={[0, 2.318, -0.011]} rotation={[-Math.PI, -1.507, -Math.PI]} scale={0.163}>
        <mesh geometry={nodes.Teeth001.geometry} material={materials['Tongue.001']} />
        <mesh geometry={nodes.Teeth001_1.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Teeth001_2.geometry} material={materials.PaletteMaterial004} />
      </group>
      <mesh geometry={nodes.Hand.geometry} material={materials['Hand.001']} position={[-0.283, 1.438, -0.373]} rotation={[-2.229, -0.354, -0.261]} scale={0.163} />
    </group>
  )
}

useGLTF.preload('/wednesday-draco-transformed.glb')
