/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\platform-draco.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Platform(props) {
  const { nodes, materials } = useGLTF('/platform-draco-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.017, -0.722, 0.88]} scale={[7.431, 0.425, 7.431]}>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials['Artificial Marble 1']} />
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['Green marble']} />
      </group>
    </group>
  )
}

useGLTF.preload('/platform-draco-transformed.glb')
