/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 .\public\doors-draco.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/doors-draco.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.StoneGateway003.geometry} material={materials['monastery_stone_floor.003']} position={[7.842, 3.889, 0.77]} rotation={[Math.PI / 2, 0, 1.488]} />
      <mesh geometry={nodes.StoneGateway002.geometry} material={materials['monastery_stone_floor.002']} position={[6.551, 3.889, 4.439]} rotation={[Math.PI / 2, 0, 2.482]} />
      <mesh geometry={nodes.StoneGateway001.geometry} material={materials['monastery_stone_floor.001']} position={[6.551, 3.889, -3.035]} rotation={[Math.PI / 2, 0, 0.801]} />
    </group>
  )
}

useGLTF.preload('/doors-draco.glb')
