/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\dome-draco.glb --transform scale: [0.75, 0.75, 0.75]
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Dome(props) {
  const { nodes, materials } = useGLTF('/dome-draco-transformed.glb')
  return (
     <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder003.geometry} material={materials['Black and gold marble']} position={[-0.089, -0.138, -0.208]} scale={[10.372, 0.103, 10.372]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Green marble.002']} position={[0.002, 6.203, 5.487]} scale={[6, 1.2, 6]} />
      <group position={[-0.089, -0.542, 5.473]} scale={[7.431, 0.425, 7.431]}>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials['Artificial Marble 1']} />
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials.PaletteMaterial001} />
      </group>
      <mesh geometry={nodes.Roof.geometry} material={materials.PaletteMaterial002} position={[0.088, 6.636, 5.32]} scale={5} />
    </group>
  )
}

useGLTF.preload('/dome-draco-transformed.glb')
