/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\LeftDoor.glb --transform scale: [0.75, 0.75, 0.75]
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LeftDoor(props) {
  const { nodes, materials } = useGLTF('/LeftDoor-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.StoneGateway001.geometry} material={materials['Green marble']} position={[4.433, 2.5, 7.884]} rotation={[-Math.PI / 2, 0, -2.094]} scale={-1} />
      <group position={[4.461, -0.496, 7.898]} rotation={[-3.131, -1.03, -3.133]} scale={6.655}>
        <mesh geometry={nodes.mesh003.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.mesh003_1.geometry} material={materials.PaletteMaterial002} />
      </group>
    </group>
  )
}

useGLTF.preload('/LeftDoor-transformed.glb')
