/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\MiddleDoor.glb --transform scale: [0.75, 0.75, 0.75]
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function MiddleDoor(props) {
  const { nodes, materials } = useGLTF('/MiddleDoor-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.StoneGateway003.geometry} material={materials['Green marble']} position={[0.226, 2.529, 10.127]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={-1} />
      <group position={[0.228, -0.482, 10.159]} rotation={[-3.136, 0.017, 3.142]} scale={6.655}>
        <mesh geometry={nodes.mesh002.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.mesh002_1.geometry} material={materials.PaletteMaterial002} />
      </group>
    </group>
  )
}

useGLTF.preload('/MiddleDoor-transformed.glb')
