/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\RightDoor.glb --transform scale: [0.75, 0.75, 0.75]
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RightDoor(props) {
  const { nodes, materials } = useGLTF('/RightDoor-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.StoneGateway002.geometry} material={materials['Green marble']} position={[-4.192, 2.55, 8.021]} rotation={[-Math.PI / 2, 0, 2.12]} scale={-1} />
      <group position={[-4.218, -0.446, 8.039]} rotation={[-3.131, 1.038, 3.133]} scale={6.655}>
        <mesh geometry={nodes.mesh004.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.mesh004_1.geometry} material={materials.PaletteMaterial002} />
      </group>
    </group>
  )
}

useGLTF.preload('/RightDoor-transformed.glb')
