/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\earth-draco.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Earth(props) {
  const { nodes, materials } = useGLTF('/earth-draco-transformed.glb')
  const ref = useRef()

  useFrame(() => {
    ref.current.rotation.y += 0.001
  })

  return (
    <group dispose={null}>
      <mesh ref={ref} geometry={nodes.Earth.geometry} material={materials.Earth} position={[58.175, 13.474, 131.772]} rotation={[0.363, -0.244, 0.092]} scale={10.641} />
    </group>
  )
}

useGLTF.preload('/earth-draco-transformed.glb')
