/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\moon-draco.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Moon(props) {
  const { nodes, materials } = useGLTF('/moon-draco-transformed.glb')
  const ref = useRef()

  useFrame(() => {
    ref.current.rotation.y += 0.001
  })

  return (
    <group {...props} dispose={null}>
      <mesh ref={ref} geometry={nodes.Mercury.geometry} material={materials.Mercury} position={[58.216, 13.945, 131.035]} rotation={[0.37, 0.307, -0.117]} scale={1.981} />
    </group>
  )
}

useGLTF.preload('/moon-draco-transformed.glb')
