/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 .\public\greek_temple-draco.glb --transform scale: [0.25,0.25,0.25]
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function GreekTemple(props) {
  const { nodes, materials } = useGLTF('/greek_temple-draco-transformed.glb')
  return (
      <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.objStructure_1.geometry} material={materials['Grass Leaves']} />
        <mesh geometry={nodes.objStructure_2.geometry} material={materials['Marble Polished Slab 001a']} />
        <mesh geometry={nodes.objStructure_3.geometry} material={materials['Piano Black With Fingerprints Plastic PL']} />
      </group>
    </group>
  )
}

useGLTF.preload('/greek_temple-draco-transformed.glb')