/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 .\public\themis-shrine-draco.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ThemisShrine(props) {
  const { nodes, materials } = useGLTF('/themis-shrine-draco-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.014, 4.507, -1.58]} rotation={[-0.391, 0.053, 0.008]} scale={0.015}>
        <mesh geometry={nodes.Icosphere011.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Icosphere011_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Icosphere011_2.geometry} material={materials['Material.006']} />
      </group>
      <group position={[0, 0, -1.676]}>
        <mesh geometry={nodes.Cylinder.geometry} material={materials['Cracked glass']} />
        <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Artificial Marble 8']} />
      </group>
      <group position={[0, 2.026, -1.676]} scale={[0.813, 1, 0.813]}>
        <mesh geometry={nodes.Cylinder005.geometry} material={materials['Stone Tiles']} />
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials.Stone} />
      </group>
    </group>
  )
}

useGLTF.preload('/themis-shrine-draco-transformed.glb')
